---

- name: Get zabbix api token
  uri:
    url: "{{ zabbix_api_url }}"
    body: '{
              "jsonrpc":"2.0",
              "method":"user.login",
              "params":{
                "user":"{{ zabbix_api_user }}",
                "password":"{{ zabbix_api_password }}"
              },
              "auth":null,
              "id":7
            }'
    body_format: json
  register: zabbix_api_token
